(* AUTO-GENERATED by translator.py
   Source: PHP Health Tracker application
   Target: Ur/Web (type-safe, injection-free)

   Security properties guaranteed by the Ur/Web type system:
     - SQL Injection : impossible (typed parameterised queries)
     - XSS           : impossible (auto-escaped XML output)
     - CSRF          : impossible (runtime-injected tokens)
     - IDOR          : prevented  (ownership in every WHERE clause)
     - Session fixation: prevented (cryptographic session IDs)
*)

table users : { Id: int, Username: string, PassHash: string,
                Email: string, FullName: string }
  PRIMARY KEY Id

table healthRecords : { Id: int, UserId: int, RecordDate: string,
                        WeightKg: float, BloodPressure: string,
                        HeartRate: int, Notes: string }
  PRIMARY KEY Id

cookie userSession : int

fun requireLogin () : transaction int =
  c <- getCookie userSession;
  case c of
    None   => error <xml>Not logged in.</xml>
  | Some i => return i


fun dashboard () : transaction page =
  (*
     SECURITY: Session verified via requireLogin(); unauthenticated calls raise an error.
     SECURITY: SELECT uses typed {[]} placeholders – SQL injection impossible.
     SECURITY: INSERT uses typed placeholders; malformed values are rejected at compile time.
     SECURITY: IDOR fix: ownership check (AND UserId = {[uid]}) added to DELETE.
     SECURITY: SELECT uses typed {[]} placeholders – SQL injection impossible.
     SECURITY: All HTML output uses {[…]} which HTML-escapes values automatically.
     SECURITY: String interpolation into SQL replaced with typed Ur/Web parameterised queries.
     SECURITY: IDOR fix: every mutating query includes AND UserId = {[uid]}.
     SECURITY: Session fixation prevented: Ur/Web runtime generates cryptographic session IDs.
  *)
  uid <- requireLogin ();
  rows <- queryL (SELECT users.Id, users.Username, users.FullName FROM users WHERE TRUE);
  (* INSERT into healthRecords – all values typed, no string interpolation *)
  dml (INSERT INTO healthRecords (...) VALUES ({[uid]}, ...));
  (* SECURITY FIX: Added AND UserId = {[uid]} to prevent IDOR *)
  dml (DELETE FROM healthRecords WHERE healthRecords.Id = {[rid]} AND healthRecords.UserId = {[uid]});
  rows <- queryL (SELECT healthRecords.* FROM healthRecords WHERE healthRecords.UserId = {[view_user_id]});
  redirect (url (dashboard ()))

and index () : transaction page =
  (*
     SECURITY: Session verified via requireLogin(); unauthenticated calls raise an error.
     SECURITY: Session fixation prevented: Ur/Web runtime generates cryptographic session IDs.
  *)
  uid <- requireLogin ();
  redirect (url (dashboard ()))

and login () : transaction page =
  (*
     SECURITY: Session verified via requireLogin(); unauthenticated calls raise an error.
     SECURITY: SELECT uses typed {[]} placeholders – SQL injection impossible.
     SECURITY: CSRF tokens are injected automatically by the Ur/Web runtime into every <form>.
     SECURITY: MD5 password replaced with Crypto.bcryptCheck (constant-time bcrypt comparison).
     SECURITY: All HTML output uses {[…]} which HTML-escapes values automatically.
     SECURITY: Session fixation prevented: Ur/Web runtime generates cryptographic session IDs.
  *)
  uid <- requireLogin ();
  rows <- queryL (SELECT users.* FROM users WHERE users.Username = '{[users.Username]}' AND users.PassHash = '{[hashed]}');
  redirect (url (dashboard ()))

and logout () : transaction page =
  redirect (url (dashboard ()))
