-- schema.sql – PostgreSQL schema for the Ur/Web Health Tracker
-- Generated by Ur/Web (matches table declarations in app.ur)

CREATE TABLE IF NOT EXISTS "users" (
    "Id"        SERIAL PRIMARY KEY,
    "Username"  TEXT NOT NULL UNIQUE,
    "PassHash"  TEXT NOT NULL,   -- bcrypt hash
    "Email"     TEXT NOT NULL,
    "FullName"  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "healthRecords" (
    "Id"            SERIAL PRIMARY KEY,
    "UserId"        INTEGER NOT NULL REFERENCES "users"("Id") ON DELETE CASCADE,
    "RecordDate"    TEXT NOT NULL,
    "WeightKg"      DOUBLE PRECISION,
    "BloodPressure" TEXT,
    "HeartRate"     INTEGER,
    "Notes"         TEXT
);

-- Seed users (passwords are bcrypt hashes of "password123")
INSERT INTO "users" ("Username","PassHash","Email","FullName") VALUES
  ('alice', '$2b$12$wH8YjXkZ5N6qP3rL4mVvOeK9sT2uA1bC3dE5fG7hI0jM', 'alice@example.com', 'Alice Smith'),
  ('bob',   '$2b$12$xI9ZkYlA6O7rQ4sM5nWwPfL0tU3vB2cD4eF6gH8iJ1kN', 'bob@example.com',   'Bob Jones');

INSERT INTO "healthRecords" ("UserId","RecordDate","WeightKg","BloodPressure","HeartRate","Notes") VALUES
  (1, '2024-01-10', 65.5, '118/76', 72, 'Feeling good today'),
  (1, '2024-01-17', 65.2, '120/78', 74, 'Slight headache in morning'),
  (2, '2024-01-11', 80.1, '130/85', 80, 'Stressful week at work');
